server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:\Users\Jim\IdeaProjects\native-file-repo
        git:
#          uri: file:///C:\Users\Jim\IdeaProjects\git-local-repo
          uri: https://github.com/BKJIN/spring-cloud-config
#          username: # private ???
#          password: # private ???
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
